# Generated by Django 5.1.2 on 2024-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('matricula', models.CharField(editable=False, max_length=10, unique=True)),
                ('curso', models.CharField(choices=[('Engenharia de Software', 'Engenharia de Software'), ('Sistemas de Informação', 'Sistemas de Informação'), ('Ciências da Computação', 'Ciências da Computação')], max_length=50)),
                ('campus', models.CharField(choices=[('Palmas', 'Palmas'), ('Porto Nacional', 'Porto Nacional'), ('Arraias', 'Arraias')], max_length=20)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/')),
                ('situacao', models.CharField(choices=[('Vinculado', 'Vinculado'), ('Formado', 'Formado'), ('Jubilado', 'Jubilado'), ('Evadido', 'Evadido')], max_length=20)),
                ('forma_ingresso', models.CharField(choices=[('Vestibular', 'Vestibular'), ('SISU', 'SISU'), ('PSEnem', 'PSEnem')], max_length=20)),
            ],
        ),
    ]
