# Generated by Django 5.1.3 on 2024-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0003_campus_alter_aluno_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
