# Generated by Django 5.1.3 on 2024-11-08 22:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0005_curso_unique_curso_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.RemoveConstraint(
            model_name='curso',
            name='unique_curso_campus',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='fabrica.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='fabrica.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.CharField(choices=[('Vestibular', 'Vestibular'), ('SISU', 'SISU'), ('PSEnem', 'PSEnem')], max_length=20, verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos_fotos/', verbose_name='Foto do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('Vinculado', 'Vinculado'), ('Formado', 'Formado'), ('Jubilado', 'Jubilado'), ('Evadido', 'Evadido')], max_length=20, verbose_name='Situação'),
        ),
    ]
