# Generated by Django 5.1.3 on 2024-11-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0006_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Forma de Ingresso',
                'verbose_name_plural': 'Formas de Ingresso',
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='fabrica.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='fabrica.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='fabrica.campus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='fabrica.formaingresso', verbose_name='Forma de Ingresso'),
        ),
    ]
