# Generated by Django 5.1.3 on 2024-11-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0007_formaingresso_alter_aluno_campus_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formaingresso',
            options={'verbose_name': 'ingresso', 'verbose_name_plural': 'formaIngresso'},
        ),
    ]
