# Generated by Django 5.1.3 on 2024-11-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0008_alter_formaingresso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.CharField(choices=[('Vestibular', 'Vestibular'), ('SISU', 'SISU'), ('PSEnem', 'PSEnem')], max_length=20, verbose_name='Forma de Ingresso'),
        ),
        migrations.DeleteModel(
            name='FormaIngresso',
        ),
    ]
