# Generated by Django 5.1.3 on 2024-11-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0009_alter_aluno_forma_ingresso_delete_formaingresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ingresso',
                'verbose_name_plural': 'formaIngresso',
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='fabrica.formaingresso', verbose_name='Forma de Ingresso'),
        ),
    ]
