# Generated by Django 5.1.3 on 2024-11-11 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0010_formaingresso_alter_aluno_forma_ingresso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='formaingresso',
            options={'verbose_name': 'Ingresso', 'verbose_name_plural': 'formaIngresso'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='aluno',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='Número de cpf sem digitos ou pontos', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(default=datetime.date.today, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrica.formaingresso', verbose_name='Forma de cadastro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos_fotos/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(max_length=500, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Vinculado'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Evadido')], verbose_name='Situação'),
        ),
    ]
