# Generated by Django 5.1.3 on 2024-11-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0011_alter_curso_options_alter_formaingresso_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_ingresso',
            new_name='dataIngresso',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='forma_ingresso',
            new_name='formaIngresso',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='nome_completo',
            new_name='nomeCompleto',
        ),
    ]
