# Generated by Django 5.1.3 on 2024-11-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0012_rename_data_ingresso_aluno_dataingresso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='campus',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='FormaIngresso',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
