# Generated by Django 5.1.3 on 2024-11-12 13:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'formaIngresso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='Piloto.campus')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=500, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Matricula')),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/')),
                ('situacao', models.IntegerField(choices=[(1, 'Vinculado'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Evadido')], verbose_name='Situação')),
                ('dataIngresso', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='data de cadastro')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Piloto.campus', verbose_name='Campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Piloto.curso', verbose_name='Curso')),
                ('formaIngresso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Piloto.formaingresso', verbose_name='Forma de cadastro')),
            ],
        ),
    ]
