# Generated by Django 5.1.3 on 2024-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Situacao',
                'verbose_name_plural': 'Situacoes',
            },
        ),
    ]
