# Generated by Django 5.1.3 on 2024-11-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0003_alter_aluno_formaingresso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Piloto.situacao', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
