# Generated by Django 5.1.3 on 2024-11-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0004_alter_situacao_options_alter_aluno_situacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='dataIngresso',
            new_name='dataCadastro',
        ),
    ]
