# Generated by Django 5.1.3 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0005_rename_dataingresso_aluno_datacadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dataUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
