# Generated by Django 5.1.3 on 2024-11-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0006_aluno_ativo_aluno_dataupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='campus',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima atualização'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='Piloto.situacao', verbose_name='Situação'),
        ),
    ]
