# Generated by Django 5.1.3 on 2024-11-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0007_alter_aluno_options_remove_aluno_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='estaNaInstituicao',
            field=models.BooleanField(default=True, verbose_name='Aluno vinculado na instituição?'),
        ),
        migrations.AddField(
            model_name='situacao',
            name='name',
            field=models.CharField(default='default_name', max_length=10, unique=True, verbose_name='Nome da Situação'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos_fotos/', verbose_name='foto Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Piloto.situacao', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
