# Generated by Django 5.1.3 on 2024-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0008_situacao_estanainstituicao_situacao_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='name',
            field=models.CharField(default='default_name', max_length=10, verbose_name='Nome da Situação'),
        ),
    ]
