# Generated by Django 5.1.3 on 2024-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Piloto', '0009_alter_situacao_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
